### ISSUE TITLE
[BUG]Exception encountered while processing metadata file: file:///Users/antonminakov/Documents/Projects/support-admin-panel/support-admin-panel/build/classes/java/main/META-INF/spring-configuration-metadata.json

### ISSUE THREAD

**Issue by antonminakov** [flikas/archived-idea-spring-boot-assistant#15]
## What happened
> Please describe what you were doing when this exception occurred.

## Expected behavior
> A clear and concise description of what you expected to happen.

## Screenshots
> If applicable, add screenshots to help explain your problem.

## Version information
- OS: `Mac OS X 12.4 x86_64`
- IDE: `IntelliJ IDEA 2022.2 EAP(IU-222.2680.4)`
- Plugin: `Spring Boot Assistant 0.14.0`

## Exception
Exception encountered while processing metadata file: file:///Users/antonminakov/Documents/Projects/support-admin-panel/support-admin-panel/build/classes/java/main/META-INF/spring-configuration-metadata.json

<details><summary>Stack trace</summary>

```
java.io.FileNotFoundException: /Users/antonminakov/Documents/Projects/support-admin-panel/support-admin-panel/build/classes/java/main/META-INF/spring-configuration-metadata.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.getInputStream(LocalFileSystemBase.java:465)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getInputStream(PersistentFSImpl.java:661)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.getInputStream(VirtualFileImpl.java:110)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.processContainers(SuggestionServiceImpl.java:342)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$11(SuggestionServiceImpl.java:269)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$12(SuggestionServiceImpl.java:259)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

## Additional context
> Add any other context about the problem here.

**Comment by flikas** [comment]
emm...is this happens all the time, or just once?

**Comment by antonminakov** [comment]
> emm...is this happens all the time, or just once?

I've faced the issue just once as of now.

**Comment by flikas** [comment]
ok, I will try to do some stability improvements.
