### ISSUE TITLE
[BUG]Exception encountered while processing metadata file: jar:///Users/Thomas.Voosen/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-circuitbreaker-resilience4j/2.1.2/ef042b7c59f6c151aa9430c93aad1909e8d7da35/spring-cloud-circuitbreaker-resilience4j-2.1.2.jar!/META-INF/additional-spring-configuration-metadata.json

### ISSUE THREAD

**Issue by rd-thomas-voosen** [flikas/archived-idea-spring-boot-assistant#27]
## What happened
> Please describe what you were doing when this exception occurred.

## Expected behavior
> A clear and concise description of what you expected to happen.

## Screenshots
> If applicable, add screenshots to help explain your problem.

## Version information
- OS: `Mac OS X 12.4 x86_64`
- IDE: `IntelliJ IDEA 2022.1.1(IU-221.5591.52)`
- Plugin: `Spring Boot Assistant 0.14.0`

## Exception
Exception encountered while processing metadata file: jar:///Users/Thomas.Voosen/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-circuitbreaker-resilience4j/2.1.2/ef042b7c59f6c151aa9430c93aad1909e8d7da35/spring-cloud-circuitbreaker-resilience4j-2.1.2.jar!/META-INF/additional-spring-configuration-metadata.json

<details><summary>Stack trace</summary>

```
java.nio.file.NoSuchFileException: /Users/Thomas.Voosen/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-circuitbreaker-resilience4j/2.1.2/ef042b7c59f6c151aa9430c93aad1909e8d7da35/spring-cloud-circuitbreaker-resilience4j-2.1.2.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1839)
	at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:19)
	at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:15)
	at com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:45)
	at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:39)
	at com.intellij.openapi.vfs.impl.ZipHandler.acquireZipHandle(ZipHandler.java:46)
	at com.intellij.openapi.vfs.impl.ZipHandlerBase.getInputStream(ZipHandlerBase.java:108)
	at com.intellij.openapi.vfs.newvfs.ArchiveFileSystem.getInputStream(ArchiveFileSystem.java:219)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getInputStream(PersistentFSImpl.java:661)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.getInputStream(VirtualFileImpl.java:110)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.processContainers(SuggestionServiceImpl.java:342)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$11(SuggestionServiceImpl.java:269)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$12(SuggestionServiceImpl.java:259)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

## Additional context
> Add any other context about the problem here.

**Comment by flikas** [comment]
Could you please give steps to reproduce this problem?
