### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'xx.xx.main' (disposed)

### ISSUE THREAD

**Issue by zj970** [flikas/archived-idea-spring-boot-assistant#287]
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'ManagerAppClient.app.staticlib.main' (disposed)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.intellij.serviceContainer.ComponentManagerImpl.checkState(ComponentManagerImpl.kt:199)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:593)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.intellij.openapi.roots.ModuleRootManagerEx.getInstanceEx(ModuleRootManagerEx.java:34)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.android.tools.idea.gradle.project.sync.setup.post.ProjectStructureUsageTracker$doTrackProjectStructure$countExternalLibraries$1.invoke(ProjectStructureUsageTracker.kt:90)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.android.tools.idea.gradle.project.sync.setup.post.ProjectStructureUsageTracker$doTrackProjectStructure$countExternalLibraries$1.invoke(ProjectStructureUsageTracker.kt:90)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.android.tools.idea.gradle.project.sync.setup.post.ProjectStructureUsageTracker.doTrackProjectStructure$countExternalLibraries(ProjectStructureUsageTracker.kt:267)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.android.tools.idea.gradle.project.sync.setup.post.ProjectStructureUsageTracker.doTrackProjectStructure(ProjectStructureUsageTracker.kt:201)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.android.tools.idea.gradle.project.sync.setup.post.ProjectStructureUsageTracker.trackProjectStructure$lambda$0(ProjectStructureUsageTracker.kt:69)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
10月 27 10:38:01 HIGHFREEDOM plasmashell[2459]:         at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zj970** [comment]
当我尝试打开第三个从gitee下载的项目出现卡死
