### ISSUE TITLE
Plugin crashed

### ISSUE THREAD

**Issue by domax** [flikas/archived-idea-spring-boot-assistant#29]
## What happened
Just opened one of project's YAML configuration files

## Version information
- OS: `Windows Server 2016 10.0 amd64`
- IDE: `IntelliJ IDEA 2022.1.3(IU-221.5921.22)`
- Plugin: `Spring Boot Assistant 0.14.3`

## Exception
Unhandled exception in [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelling}@489e2c28, Dispatchers.Default]

<details><summary>Stack trace</summary>

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiClassImpl #JAVA 
invalidated at: see attachment
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:243)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getProject(StubBasedPsiElementBase.java:276)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy.getTarget(ClassMetadataProxy.java:174)
	at in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy.doWithTargetAndReturn(ClassMetadataProxy.java:161)
	at in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy.getPsiType(ClassMetadataProxy.java:146)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.json.SpringConfigurationMetadataGroup.getDocumentation(SpringConfigurationMetadataGroup.java:74)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.getDocumentationForKey(MetadataNonPropertySuggestionNode.java:398)
	at in.oneton.idea.spring.assistant.plu

**Comment by flikas** [comment]
Can this problem to be reproduced?
