### ISSUE TITLE
2023.3 插件失效了

### ISSUE THREAD

**Issue by ydq** [flikas/archived-idea-spring-boot-assistant#309]
## What happened
IDEA 2023.3 失效了，所有的属性都无法识别，全部标记为红色

## To Reproduce
下载升级最新的 IDEA 2023.3 RC 插件报错失效

## Screenshots
<img width="504" alt="image" src="https://github.com/flikas/idea-spring-boot-assistant/assets/8097340/fc11df21-f8f1-4c6a-a371-a7d76bc32dd0">

## Version information
IntelliJ IDEA 2023.3 RC (Community Edition)
Build #IC-233.11799.196, built on November 29, 2023
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  ide.experimental.ui.inter.font=true
Non-Bundled Plugins:
  dev.flikas.idea.spring.boot.assistant.plugin (222.17.2)

## Exception
java.lang.NoClassDefFoundError: org/apache/commons/lang/time/StopWatch
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$11(SuggestionServiceImpl.java:258)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:122)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$12(SuggestionServiceImpl.java:255)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.time.StopWatch PluginClassLoader(plugin=PluginDescriptor(name=Spring Boot Assistant, id=dev.flikas.idea.spring.boot.assistant.plugin, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.3/plugins/idea-spring-boot-assistant, version=222.17.2, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 16 more

**Comment by ydq** [comment]
看到已经有重复的问题报告了，暂时关闭了
