### ISSUE TITLE
Exception in yml file

### ISSUE THREAD

**Issue by rbleuse** [flikas/archived-idea-spring-boot-assistant#5]
Hi, just type some properties manually and I face regularly this exception :

<img width="620" alt="2022-02-02_10h24_29" src="https://user-images.githubusercontent.com/626863/152078794-f6049a64-608d-4cc8-8aa5-3537986b36c4.png">

<details><summary>Stack trace</summary>

```
com.intellij.diagnostic.PluginException: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field arg$1 in class in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy$$Lambda$7424/0x00000001036d2840 has non-equivalent values:
  in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy@7f8a29a5 (in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy) and
  in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy@34b37464 (in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method. [Plugin: dev.flikas.idea.spring.boot.assistant.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:100)
	at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:164)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:131)
	at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:127)
	at com.intellij.util.CachedValueStabilityChecker.checkProvidersEquivalent(CachedValueStabilityChecker.java:83)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:67)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy.getTarget(ClassMetadataProxy.java:174)
	at in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy.doWithTargetAndReturn(ClassMetadataProxy.java:161)
	at in.oneton.idea.spring.assistant.plugin.suggestion.clazz.ClassMetadataProxy.getSuggestionNodeType(ClassMetadataProxy.java:140)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.json.SpringConfigurationMetadataProperty.getSuggestionNodeType(SpringConfigurationMetadataProperty.java:264)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.json.SpringConfigurationMetadataProperty.isLeaf(SpringConfigurationMetadataProperty.java:253)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataPropertySuggestionNode.findKeySuggestionsForQueryPrefix(MetadataPropertySuggestionNode.java:161)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.addChildToMatchesAndSearchInNextLevel(MetadataNonPropertySuggestionNode.java:530)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.findKeySuggestionsForQueryPrefix(MetadataNonPropertySuggestionNode.java:316)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.addChildToMatchesAndSearchInNextLevel(MetadataNonPropertySuggestionNode.java:530)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.findKeySuggestionsForQueryPrefix(MetadataNonPropertySuggestionNode.java:316)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.addChildToMatchesAndSearchInNextLevel(MetadataNonPropertySuggestionNode.java:530)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.findKeySuggestionsForQueryPrefix(MetadataNonPropertySuggestionNode.java:316)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataSuggestionNode.findKeySuggestionsForQueryPrefix(MetadataSuggestionNode.java:39)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.doFindSuggestionsForQueryPrefix(SuggestionServiceImpl.java:297)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.doFindSuggestionsForQueryPrefix(SuggestionServiceImpl.java:276)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.findSuggestionsForQueryPrefix(SuggestionServiceImpl.java:194)
	at in.oneton.idea.spring.assistant.plugin.suggestion.completion.YamlCompletionProvider.addCompletions(YamlCompletionProvider.java:103)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:25)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:158)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:89)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:25)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:158)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:60)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:133)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:41)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$12(CompletionProgressIndicator.java:865)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:172)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:600)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:171)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:861)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:849)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:352)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:344)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:681)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:606)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

Using Intellij 2022.1 EAP

**Comment by flikas** [comment]
I have got this exception too, working on it.
