### ISSUE TITLE
Exception when importing project

### ISSUE THREAD

**Issue by rbleuse** [flikas/archived-idea-spring-boot-assistant#7]
Hi, just got this exception after importing a fresh project from Spring starter :

<img width="825" alt="Screen Shot 2022-02-15 at 15 03 00" src="https://user-images.githubusercontent.com/626863/154002133-68af441c-e714-4c8b-930a-32d13e0738e7.png">

<details><summary>Stack trace</summary>

```
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =enabled (class java.lang.String), hashCode=-1609594047; object #2 =enabled (class java.lang.String), hashCode=-1609594047
	at gnu.trove.TObjectHash.throwObjectContractViolation(TObjectHash.java:331)
	at gnu.trove.THashMap.rehash(THashMap.java:347)
	at gnu.trove.THash.postInsertHook(THash.java:285)
	at gnu.trove.THashMap.put(THashMap.java:174)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.addProperty(MetadataNonPropertySuggestionNode.java:486)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.addChildren(MetadataNonPropertySuggestionNode.java:251)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.addPropertiesToIndex(SuggestionServiceImpl.java:582)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.buildMetadataHierarchy(SuggestionServiceImpl.java:484)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.processContainers(SuggestionServiceImpl.java:444)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.reindexModule(SuggestionServiceImpl.java:355)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reIndex$2(SuggestionServiceImpl.java:106)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reIndex$3(SuggestionServiceImpl.java:95)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

Using Intellij 2021.3.2

**Comment by flikas** [comment]
Could you please paste your pom?

**Comment by rbleuse** [comment]
Here is the project I imported when receiving the exception (you can check the `build.gradle.kts`) :

https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=2.6.3&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=validation,web,devtools,actuator,data-cassandra

I downloaded this exact gradle project and imported into intellij 2021.3.2

**Comment by flikas** [comment]
May be there is some concurrent modification problem.
Please try this new version: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=154704

**Comment by flikas** [comment]
May be there is some concurrent modification problem.
Please try this new version: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=164546

**Comment by rbleuse** [comment]
I can't really tell if it's fixed or not, I imported some new projects and didn't get this error anymore (got it only once), before I created this issue.

It was probably a random exception in a very rare situation.
I'll close this issue and reopen it if it still happen.

Thank you !
