### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by feirnova** [flikas/archived-idea-spring-boot-assistant#9]
![1](https://user-images.githubusercontent.com/15042986/158759475-8392398f-7066-4263-838f-a534c3bc94e1.png)
如图↑
错误内容↓
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataContainerInfo.getContainerFile(MetadataContainerInfo.java:66)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataContainerInfo.newInstances(MetadataContainerInfo.java:90)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.computeNewContainersToProcess(SuggestionServiceImpl.java:364)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.reindexModule(SuggestionServiceImpl.java:346)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$8(SuggestionServiceImpl.java:139)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$9(SuggestionServiceImpl.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by flikas** [comment]
试试这个版本？https://plugins.jetbrains.com/plugin/download?rel=true&updateId=164546

**Comment by flikas** [comment]
This issue is closed due to inactivity. Feel free to open a new one if this problem happens again.
